<?php
$links = [
    [
        'type' => 'header',
        'title' => 'Principal'
    ],
    [
        'type' => 'link',
        'title' => 'Dashboard',
        'icon' => 'fa-solid fa-gauge',
        'route' => 'admin.dashboard',
        'active' => 'admin.dashboard',
        'can' => ['access_dashboard'],
    ],
    [
        'type' => 'group',
        'title' => 'Inventario',
        'icon' => 'fa-solid fa-boxes-stacked',
        'active' => [
            'admin.categories.*',
            'admin.products.*',
            'admin.variants.*',
            'admin.warehouses.*',
            'admin.attributes.*',
        ],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Categorías',
                'route' => 'admin.categories.index',
                'active' => 'admin.categories.*',
                'can' => ['read_categories'],
            ],
            [
                'type' => 'link',
                'title' => 'Productos',
                'route' => 'admin.products.index',
                'active' => 'admin.products.*',
                'can' => ['read_products'],
            ],
            [
                'type' => 'link',
                'title' => 'Variantes',
                'route' => 'admin.variants.index',
                'active' => 'admin.variants.*',
                'can' => ['read_variants'],
            ],
            [
                'type' => 'link',
                'title' => 'Almacenes',
                'route' => 'admin.warehouses.index',
                'active' => 'admin.warehouses.*',
                'can' => ['read_warehouses'],
            ],
            [
                'type' => 'link',
                'title' => 'Atributos',
                'route' => 'admin.attributes.index',
                'active' => 'admin.attributes.*',
                'can' => ['read_attributes'],
            ],
        ],
    ],

    [
        'type' => 'group',
        'title' => 'Compras',
        'icon' => 'fa-solid fa-cart-shopping',
        'route' => '#',
        'active' => ['admin.suppliers.*', 'admin.purchases-orders.*', 'admin.purchases.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Proveedores',
                'route' => 'admin.suppliers.index',
                'active' => 'admin.suppliers.*',
                'can' => ['read_suppliers'],
            ],
            [
                'type' => 'link',
                'title' => 'Compras',
                'route' => 'admin.purchases.index',
                'active' => 'admin.purchases.*',
                'can' => ['read_purchases'],
            ],
        ],
    ],
    [
        'type' => 'group',
        'title' => 'Ventas',
        'icon' => 'fa-solid fa-cash-register',
        'active' => ['admin.customers.*', 'admin.quotes.*', 'admin.sales.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Clientes',
                'route' => 'admin.customers.index',
                'active' => 'admin.customers.*',
                'can' => ['read_customers'],
            ],
            [
                'type' => 'link',
                'title' => 'Cotizaciones',
                'route' => 'admin.quotes.index',
                'active' => 'admin.quotes.*',
                'can' => ['read_quotes'],
            ],
            [
                'type' => 'link',
                'title' => 'Ventas',
                'route' => 'admin.sales.index',
                'active' => 'admin.sales.*',
                'can' => ['read_sales'],
            ],
        ],
    ],
    [
        'type' => 'group',
        'title' => 'Movimientos',
        'icon' => 'fa-solid fa-arrows-rotate',
        'route' => '#',
        'active' => ['admin.movements.*', 'admin.transfers.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Movimientos',
                'route' => 'admin.movements.index',
                'active' => 'admin.movements.*',
                'can' => ['read_movements'],
            ],
            [
                'type' => 'link',
                'title' => 'Transferencias',
                'route' => 'admin.transfers.index',
                'active' => 'admin.transfers.*',
                'can' => ['read_transfers'],
            ],
        ],
    ],

    [
        'type' => 'group',
        'title' => 'Reportes',
        'icon' => 'fa-solid fa-chart-line',
        'active' => ['admin.reports.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Ventas: Top productos',
                'route' => 'admin.reports.sales.top-products',
                'active' => 'admin.reports.sales.top-products',
                'can' => ['read_reports'],
            ],
            [
                'type' => 'link',
                'title' => 'Ventas: Métodos de pago',
                'route' => 'admin.reports.sales.payment-methods',
                'active' => 'admin.reports.sales.payment-methods',
                'can' => ['read_reports'],
            ],
            [
                'type' => 'link',
                'title' => 'Clientes: Frecuentes',
                'route' => 'admin.reports.customers.frequent',
                'active' => 'admin.reports.customers.frequent',
                'can' => ['read_reports'],
            ],
            [
                'type' => 'link',
                'title' => 'Sunat: Estados',
                'route' => 'admin.reports.sunat.status',
                'active' => 'admin.reports.sunat.status',
                'can' => ['read_reports'],
            ],
        ],
    ],
    [
        'type' => 'group',
        'title' => 'Pos',
        'icon' => 'fa-solid fa-chart-line',
        'route' => '#',
        'active' => ['admin.posconfig.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Punto de venta',
                'route' => 'admin.posconfig.index',
                'active' => 'admin.posconfig.*',
                'can' => ['read_posconfig'],
            ],
        ],
    ],
    [
        'type' => 'group',
        'title' => 'Promociones',
        'icon' => 'fa-regular fa-gift',
        'route' => '#',
        'active' => ['admin.loyalty-programs.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Promociones',
                'route' => 'admin.loyalty-programs.index',
                'active' => 'admin.loyalty-programs.*',
                'can' => ['read_loyalty-programs'],
            ],
        ],
    ],
    [
        'type' => 'header',
        'title' => 'Configuración',
    ],
    [
        'type' => 'group',
        'title' => 'Configuración',
        'icon' => 'fa-solid fa-gear',
        'route' => '#',
        'active' =>  ['admin.companies.*', 'admin.sequences.*', 'admin.journals.*'],
        'items' => [
            [
                'type' => 'link',
                'title' => 'Empresas',
                'route' => 'admin.companies.index',
                'active' => 'admin.companies.*',
                'can' => ['read_companies'],
            ],
            [
                'type' => 'link',
                'title' => 'Diarios',
                'route' => 'admin.journals.index',
                'active' => 'admin.journals.*',
                'can' => ['read_journals'],
            ],
            [
                'type' => 'link',
                'title' => 'Secuencias',
                'route' => 'admin.sequences.index',
                'active' => 'admin.sequences.*',
                'can' => ['read_sequences'],
            ],
            [
                'type' => 'link',
                'title' => 'Sunat',
                'route' => 'admin.sunat-connections.index',
                'active' => 'admin.sunat-connections.*',
                'can' => ['read_sunat-connections'],
            ],
        ],
    ],
    [
        'type' => 'link',
        'title' => 'Usuarios',
        'icon' => 'fa-solid fa-user',
        'route' => 'admin.users.index',
        'active' => 'admin.users.*',
        'can' => ['read_users'],
    ],
    [
        'type' => 'link',
        'title' => 'Roles',
        'icon' => 'fa-solid fa-users-gear',
        'route' => 'admin.roles.index',
        'active' => 'admin.roles.*',
        'can' => ['read_roles'],
    ],
    [
        'type' => 'link',
        'title' => 'Ajustes',
        'icon' => 'fa-solid fa-gear',

    ],
];
return $links;
